[package]
name = "cardgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
scryer-prolog = { git = "https://github.com/bakaq/scryer-prolog", branch = "rework_library_interface"}
